[tool.poetry]
name = "ai-playground"
version = "0.1.0"
description = ""
authors = []
license = "MIT"
readme = "README.md"
packages = [{include = "ai_playground"}]

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.27.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
